version: 2
jobs:
  script_tests:
    docker:
      - image: clojure:lein
    version: 2
    steps:
      - checkout
      - run:
          command: |
            set -ex
            lein uberjar
            # Script tests
            for i in test/resources/scripts/*
            do
                ./${i}
            done
      - store_artifacts:
          path: target/
  lein_tests:
    docker:
      - image: clojure:lein
    version: 2
    steps:
      - checkout
      - run:
          command: |
            set -ex
            lein test2junit
            ls target/test-results
      - store_artifacts:
          path: target/test-results/xml/
      - store_artifacts:
          path: target/test-results/html/
      - store_test_results:
          path: target/test-results/xml/
workflows:
  version: 2
  build_and_test:
    jobs:
      - script_tests
      - lein_tests
