version: 2
jobs:
  lein_tests:
    docker:
      - image: clojure:lein
    version: 2
    steps:
      - checkout
      - run:
          command: |
            set -ex
            lein test2junit
            ls target/test-results
            ls target/test-results/html
            lein uberjar
            buildutils/generate-manifest
      - store_artifacts:
          path: target/test-results/xml/
          destination: test-results/xml
      - store_artifacts:
          path: target/uberjar/
          destination: uberjar/
      - store_test_results:
          path: target/test-results/xml/
      - persist_to_workspace:
          root: .
          paths:
            - target/uberjar/degasolv-*-standalone.jar
            - target/manifest

  script_tests:
    docker:
      - image: djhaskin987/lein-script-tester:latest
    version: 2
    steps:
      - checkout
      - run:
          command: |
            test/resources/scripts/test-all

  package_ubuntu16:
    docker:
      - image: djhaskin987/graal-lein-fpm:ubuntu16
    version: 2
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: cp -af /tmp/workspace/target ./
      - run:
          name: "Package debian for Ubuntu 16"
          command: buildutils/package deb
          no_output_timeout: 30m
      - persist_to_workspace:
          root: .
          paths:
            - target/package/*.deb
      - store_artifacts:
          path: target/package/
          destination: package_u16/
      - store_artifacts:
          path: target/graal/
          destination: graal_u16/

  package_ubuntu18:
    docker:
      - image: djhaskin987/graal-lein-fpm:ubuntu18
    version: 2
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: cp -af /tmp/workspace/target ./
      - run:
          name: "Package debian for Ubuntu 18"
          command: buildutils/package deb
          no_output_timeout: 30m
      - run: mv target/package target/package_u18
      - run: mv target/graal target/graal_u18
      - persist_to_workspace:
          root: .
          paths:
            - target/package_u18/*.deb
      - store_artifacts:
          path: target/package_u18/
          destination: package_u18/
      - store_artifacts:
          path: target/graal_u18/
          destination: graal_u18/

  package_centos7:
    docker:
      - image: djhaskin987/graal-lein-fpm:centos7
    version: 2
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: cp -af /tmp/workspace/target ./
      - run:
          name: "Package debian for CentOS 7"
          command: buildutils/package rpm
          no_output_timeout: 30m
      - run: mv target/package target/package_c7
      - run: mv target/graal target/graal_c7
      - persist_to_workspace:
          root: .
          paths:
            - target/package_c7/*.rpm
      - store_artifacts:
          path: target/package_c7/
          destination: package_c7/
      - store_artifacts:
          path: target/graal_c7/
          destination: graal_c7/

  test_ubuntu16_package:
    docker:
      - image: djhaskin987/test-ubuntu-installer:ubuntu16
    version: 2
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: cp -af /tmp/workspace/target ./
      - run: mv target/package_u16 target/package
      - run: buildutils/test-install-package-ubuntu

  test_ubuntu18_package:
    docker:
      - image: djhaskin987/test-ubuntu-installer:ubuntu18
    version: 2
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: cp -af /tmp/workspace/target ./
      - run: mv target/package_u18 target/package
      - run: buildutils/test-install-package-ubuntu


  test_centos7_package:
    docker:
      - image: bzohdy/centos-sudo:latest
    version: 2
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: cp -af /tmp/workspace/target ./
      - run: mv target/package_c7 target/package
      - run: buildutils/test-install-package-centos

workflows:
  version: 2
  build_and_test:
    jobs:
      - script_tests
      - lein_tests
      - package_ubuntu16:
          requires:
            - lein_tests
      - package_ubuntu18:
          requires:
            - lein_tests
      - package_centos7:
          requires:
            - lein_tests
      - test_ubuntu16_package:
          requires:
            - package_ubuntu16
      - test_ubuntu18_package:
          requires:
            - package_ubuntu16
      - test_centos7_package:
          requires:
            - package_centos7
