version: 2
jobs:
  build:
    docker:
      - image: clojure:lein
  	version: 2
  steps:
    - checkout
    - run:
        command: |
          set -ex
          lein test2junit
          lein uberjar
          # Script tests
          for i in test/resources/scripts/*
          do
              ./${i}
          done
