version: 2
jobs:
  script_tests:
    docker:
      - image: djhaskin987/lein-script-tester:latest
    version: 2
    steps:
      - checkout
      - run:
          command: |
            test/resources/scripts/test-all
  lein_tests:
    docker:
      - image: clojure:lein
    version: 2
    steps:
      - checkout
      - run:
          command: |
            set -ex
            lein test2junit
            ls target/test-results
            ls target/test-results/html
            lein uberjar
            buildutils/generate-manifest

      - persist_to_workspace:
          root: .
          paths:
            - target/uberjar/degasolv-*-standalone.jar
            - target/manifest
      - store_artifacts:
          path: target/test-results/xml/
          destination: test-results/xml
      - store_artifacts:
          path: target/uberjar/
          destination: uberjar/
      - store_test_results:
          path: target/test-results/xml/

  graal_compile:
    docker:
      - image: findepi/graalvm
    version: 2
    steps:
      - attach_workspace:
          at: /tmp/tested-artifacts
      - checkout
      - run: cp -af /tmp/tested-artifacts/target ./
      - run: buildutils/graal
      - persist_to_workspace:
          root: .
          paths:
            - target/graal/
      - store_artifacts:
          path: target/graal/
          destination: graal/
  package_ubuntu:
    docker:
      - image: alanfranz/fpm-within-docker:ubuntu-zesty
    version: 2
    steps:
      - attach_workspace:
          at: /tmp/tested-artifacts
      - checkout
      - run: cp -af /tmp/tested-artifacts/target ./
      - run: buildutils/package deb
      - persist_to_workspace:
          root: .
          paths:
            - target/package/*.deb
      - store_artifacts:
          path: target/package/
          destination: package/

  test_ubuntu_package:
    docker:
      - image: djhaskin987/test-ubuntu-installer:latest
    version: 2
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: cp -af /tmp/workspace/target ./
      - run: buildutils/test-install-package-ubuntu

  package_centos:
    docker:
      - image: alanfranz/fpm-within-docker:centos-7
    version: 2
    steps:
      - attach_workspace:
          at: /tmp/tested-artifacts
      - checkout
      - run: cp -af /tmp/tested-artifacts/target ./
      - run: buildutils/package rpm
      - persist_to_workspace:
          root: .
          paths:
            - target/package/*.rpm
      - store_artifacts:
          path: target/package/
          destination: package/

  test_centos_package:
    docker:
      - image: bzohdy/centos-sudo:latest
    version: 2
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: cp -af /tmp/workspace/target ./
      - run: buildutils/test-install-package-centos


workflows:
  version: 2
  build_and_test:
    jobs:
      - script_tests
      - lein_tests
      - graal_compile:
          requires:
            - lein_tests
      - package_ubuntu:
          requires:
            - lein_tests
      - test_ubuntu_package:
          requires:
            - package_ubuntu
      - package_centos:
          requires:
            - lein_tests
      - test_centos_package:
          requires:
            - package_centos
