version: 2
jobs:
  script_tests:
    docker:
      - image: djhaskin987/lein-script-tester:latest
    version: 2
    steps:
      - checkout
      - run:
          command: |
            test/resources/scripts/test-all

  package_ubuntu16:
    docker:
      - image: djhaskin987/graal-lein-fpm:ubuntu16
    version: 2
    steps:
      - checkout
      - run: buildutils/package deb
      - persist_to_workspace:
          root: .
          paths:
            - target/package/*.deb
      - store_artifacts:
          path: target/package/
          destination: package/
      - store_artifacts:
          path: target/test-results/xml/
          destination: test-results/xml
      - store_artifacts:
          path: target/graal/
          destination: graal/
      - store_artifacts:
          path: target/uberjar/
          destination: uberjar/
      - store_test_results:
          path: target/test-results/xml/

  package_ubuntu18:
    docker:
      - image: djhaskin987/graal-lein-fpm:ubuntu18
    version: 2
    steps:
      - checkout
      - run: buildutils/package deb
      - store_artifacts:
          path: target/package/
          destination: package/
      - store_artifacts:
          path: target/test-results/xml/
          destination: test-results/xml
      - store_artifacts:
          path: target/graal/
          destination: graal/
      - store_artifacts:
          path: target/uberjar/
          destination: uberjar/
      - store_test_results:
          path: target/test-results/xml/

  test_ubuntu_package:
    docker:
      - image: djhaskin987/test-ubuntu-installer:latest
    version: 2
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: cp -af /tmp/workspace/target ./
      - run: buildutils/test-install-package-ubuntu

  package_centos7:
    docker:
      - image: djhaskin987/graal-lein-fpm:centos7
    version: 2
    steps:
      - checkout
      - run: buildutils/package rpm
      - persist_to_workspace:
          root: .
          paths:
            - target/package/*.rpm
      - store_artifacts:
          path: target/package/
          destination: package/
      - store_artifacts:
          path: target/test-results/xml/
          destination: test-results/xml
      - store_artifacts:
          path: target/graal/
          destination: graal/
      - store_artifacts:
          path: target/uberjar/
          destination: uberjar/
      - store_test_results:
          path: target/test-results/xml/

  test_centos_package:
    docker:
      - image: bzohdy/centos-sudo:latest
    version: 2
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: cp -af /tmp/workspace/target ./
      - run: buildutils/test-install-package-centos

workflows:
  version: 2
  build_and_test:
    jobs:
      - script_tests
      - package_ubuntu16
      - package_ubuntu18
      - package_centos7
      - test_ubuntu_package:
          requires:
            - package_ubuntu16
      - test_centos_package:
          requires:
            - package_centos7
